import Foundation

/// A half-degree land and ocean bitmask of the world, in plate carrée order:
/// row 0 is 90N and column 0 is 180W.
///
/// The payload is generated by `Tools/generate-land-mask.py` and decoded once,
/// so the app carries a world map without a map service or an image asset.
public struct WorldLandMask: Sendable {
    public static let world = WorldLandMask()

    public let columns: Int
    public let rows: Int

    private let bitmap: [UInt8]

    private init() {
        columns = WorldLandMaskData.columns
        rows = WorldLandMaskData.rows
        bitmap = Self.decodedBitmap(expectedBits: columns * rows)
    }

    /// False only if the embedded payload could not be decoded, in which case
    /// every cell reads as ocean.
    public var isAvailable: Bool { !bitmap.isEmpty }

    public func isLand(row: Int, column: Int) -> Bool {
        guard row >= 0, row < rows, column >= 0, column < columns else { return false }
        let index = row * columns + column
        let byte = index >> 3
        guard byte < bitmap.count else { return false }
        return bitmap[byte] & (0x80 >> UInt8(index & 7)) != 0
    }

    public func isLand(latitude: Double, longitude: Double) -> Bool {
        let row = Int(((90 - latitude) / 180 * Double(rows)).rounded(.down))
        let column = Int(((SolarMath.wrapped180(longitude) + 180) / 360 * Double(columns)).rounded(.down))
        return isLand(
            row: min(max(row, 0), rows - 1),
            column: min(max(column, 0), columns - 1)
        )
    }

    private static func decodedBitmap(expectedBits: Int) -> [UInt8] {
        guard let deflated = Data(base64Encoded: WorldLandMaskData.deflatedBitmap) else {
            return []
        }

        do {
            let bitmap = try (deflated as NSData).decompressed(using: .zlib) as Data
            guard bitmap.count == (expectedBits + 7) / 8 else { return [] }
            return [UInt8](bitmap)
        } catch {
            return []
        }
    }
}
